package uts;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Timestamp;
import java.time.Instant;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Admin
 */
public class Absensi extends javax.swing.JFrame {
    Connection con = null;
    Statement stat;
    ResultSet res = null;
    PreparedStatement stmt;
    /**
     * Shun
     */
    public Absensi() {
        initComponents();
        Koneksi();
        datatotable();
        updateDateTime();
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateDateTime(); // Panggil method untuk memperbarui waktu dan tanggal
            }
        });
        timer.start(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        nama = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        Kembali = new javax.swing.JButton();
        nama_k = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        datetime = new javax.swing.JLabel();
        bersih = new javax.swing.JButton();
        cetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 250, -1));

        jButton1.setText("ABSEN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        nama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nama.setText("Nama Karyawan");
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 580, 275));

        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 80, -1));

        nama_k.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(nama_k, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ABSEN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(jLabel1)
                .addContainerGap(466, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 970, 60));

        datetime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(datetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        bersih.setText("Bersihkan");
        bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihActionPerformed(evt);
            }
        });
        getContentPane().add(bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        getContentPane().add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 80, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            res = stat.executeQuery("select * from karyawan where kode_karyawan='"+id.getText()+"'");
            if(res.next()){
               res = stat.executeQuery("select * from hadir where kode_karyawan = '"+id.getText()+"'");
            if(res.next())
            {
                update();
            }else{
                insert();
            } 
            }else{
                JOptionPane.showMessageDialog(null, "ID Karyawan tidak ada!");
            }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        dispose();
        new menuUtama().setVisible(true);
    }//GEN-LAST:event_KembaliActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        String nama = (String) table.getValueAt(table.getSelectedRow(), 1);
        nama_k.setText(nama);
    }//GEN-LAST:event_tableMouseClicked

    private void bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihActionPerformed
      bersih();
    }//GEN-LAST:event_bersihActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        cetak();
    }//GEN-LAST:event_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Absensi().setVisible(true);
        });
    }

    private void Koneksi(){
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/absen_k", "root", "");
            stat=con.createStatement();
            } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kembali;
    private javax.swing.JButton bersih;
    private javax.swing.JButton cetak;
    private javax.swing.JLabel datetime;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama_k;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

   private void datatotable(){
        DefaultTableModel tb= new DefaultTableModel();
        // Memberi nama pada se�ap kolom tabel
        tb.addColumn("Kode Karyawan");
        tb.addColumn("Nama Karyawan"); 
        tb.addColumn("Masuk");
        tb.addColumn("Keluar");

        table.setModel(tb);
        try{
            // Mengambil data dari database
            res=stat.executeQuery("select *from hadir");
            while (res.next()){
                
                tb.addRow(new Object[]{
                    res.getString("kode_karyawan"),
                    res.getString("nama"),
                    res.getString("masuk"),
                    res.getString("keluar"),
                    
                });
            }
         aturKolom();
        }catch (SQLException e){
        }
    } 

    private void insert() {
        try {
            String nama = null;
            res = stat.executeQuery("select * from karyawan where kode_karyawan = '"+id.getText()+"'");
            while (res.next()) {
                nama = res.getString("nama");
            }
            nama_k.setText(nama);
            stat.executeUpdate("insert into hadir (kode_karyawan,nama,masuk) values ('"+id.getText()+"','"+nama+"',NOW())");
            JOptionPane.showMessageDialog(null, "masuk");
            datatotable();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void update() {
        try {
            stat.executeUpdate("update hadir set keluar=NOW()");
            datatotable();
            JOptionPane.showMessageDialog(null, "keluar");
        } catch (Exception e) {
        }
        
        
    }

    private void updateDateTime() {
      SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss"); // Format tanggal dan waktu
      Date now = new Date(); // Dapatkan waktu sekarang
      String dateTimeStr = sdf.format(now); // Format waktu menjadi string
      datetime.setText(dateTimeStr); // Atur teks label dengan waktu ya
    }

    private void bersih() {
         int option = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin membersihkan tabel?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    
    // Periksa pilihan pengguna
    if (option == JOptionPane.YES_OPTION) {
        try {
            // Kode untuk membersihkan tabel (seperti yang telah dijelaskan sebelumnya)
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/absen_k", "root", "");
            String sql = "TRUNCATE TABLE hadir";
            Statement stmt = con.createStatement();
            stmt.executeUpdate(sql);
            stmt.close();
            con.close();
            
            // Beri notifikasi setelah berhasil membersihkan
            JOptionPane.showMessageDialog(null, "Tabel berhasil dibersihkan");
            datatotable();
            
        } catch (SQLException e) {
            // Tangani kesalahan jika ada
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
      }
    }

    private void cetak() {
            try {
            String rpt = "src/ReportAbsen/reportAbsensi.jasper"; // Path ke file laporan Jasper
            Connection con = Koneksi.getKoneksi(); // Mendapatkan koneksi ke database menggunakan method Koneksi.getKoneksi()
            JasperPrint jp = JasperFillManager.fillReport(rpt, null, con);
            // Menampilkan laporan Jasper dalam JasperViewer
            JasperViewer.viewReport(jp, false);
       } catch (JRException e) {
           System.out.println("GAGAL");
         }
            
        }

    private void aturKolom() {
        TableColumn column;
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = table.getColumnModel().getColumn(0);
        column.setPreferredWidth(150);
        column = table.getColumnModel().getColumn(1);
        column.setPreferredWidth(150);
        column = table.getColumnModel().getColumn(2);
        column.setPreferredWidth(150);
        column = table.getColumnModel().getColumn(3);
        column.setPreferredWidth(150);
        
    }

}
